// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package documents

import mock "github.com/stretchr/testify/mock"

// ValidatorMock is an autogenerated mock type for the Validator type
type ValidatorMock struct {
	mock.Mock
}

// Validate provides a mock function with given fields: oldState, newState
func (_m *ValidatorMock) Validate(oldState Document, newState Document) error {
	ret := _m.Called(oldState, newState)

	var r0 error
	if rf, ok := ret.Get(0).(func(Document, Document) error); ok {
		r0 = rf(oldState, newState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewValidatorMockT interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidatorMock creates a new instance of ValidatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidatorMock(t NewValidatorMockT) *ValidatorMock {
	mock := &ValidatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
