package ethereum

import (
	"context"
	"math/big"
	"net/url"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/CentrifugeInc/go-centrifuge/centrifuge/config"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
	"github.com/go-errors/errors"
	logging "github.com/ipfs/go-log"
)

const TransactionUnderpriced = "replacement transaction underpriced"
const NonceTooLow = "nonce too low"

var log = logging.Logger("geth-client")
var gc EthereumClient
var gcInit sync.Once

// getDefaultContextTimeout retrieves the default duration before an Ethereum call context should time out
func getDefaultContextTimeout() time.Duration {
	return config.Config.GetEthereumContextWaitTimeout()
}

func DefaultWaitForTransactionMiningContext() (ctx context.Context, cancelFunc context.CancelFunc) {
	toBeDone := time.Now().Add(getDefaultContextTimeout())
	return context.WithDeadline(context.TODO(), toBeDone)
}

// Abstract the "ethereum client" out so we can more easily support other clients
// besides Geth (e.g. quorum)
// Also make it easier to mock tests
type EthereumClient interface {
	GetClient() *ethclient.Client
	GetRpcClient() *rpc.Client
	GetHost() *url.URL
	GetNonceMutex() *sync.Mutex
}

type GethClient struct {
	Client     *ethclient.Client
	RpcClient  *rpc.Client
	Host       *url.URL
	NonceMutex *sync.Mutex
}

func (gethClient GethClient) GetClient() *ethclient.Client {
	return gethClient.Client
}

func (gethClient GethClient) GetRpcClient() *rpc.Client {
	return gethClient.RpcClient
}

func (gethClient GethClient) GetHost() *url.URL {
	return gethClient.Host
}

func (gethClient GethClient) GetNonceMutex() *sync.Mutex {
	return gethClient.NonceMutex
}

func NewClientConnection() GethClient {
	log.Info("Opening connection to Ethereum:", config.Config.GetEthereumNodeURL())
	u, err := url.Parse(config.Config.GetEthereumNodeURL())
	if err != nil {
		log.Fatalf("Failed to connect to parse ethereum.gethSocket URL: %v", err)
	}
	c, err := rpc.Dial(u.String())
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client [%s]: %v", u.String(), err)
	}
	client := ethclient.NewClient(c)
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client [%s]: %v", u.String(), err)
	}
	return GethClient{client, c, u, &sync.Mutex{}}
}

// Note that this is a singleton and is the same connection for the whole application.
func SetConnection(conn EthereumClient) {
	gcInit.Do(func() {
		gc = conn
	})
	return
}

// GetConnection returns the connection to the configured `ethereum.gethSocket`.
func GetConnection() EthereumClient {
	return gc
}

// GetGethTxOpts retrieves the geth transaction options for the given account name. The account name influences which configuration
// is used.
func GetGethTxOpts(accountName string) (*bind.TransactOpts, error) {
	account, err := config.Config.GetEthereumAccount(accountName)
	if err != nil {
		err = errors.Errorf("could not find configured ethereum key for account [%v]. please check your configuration.\n", accountName)
		log.Error(err.Error())
		return nil, err
	}

	authedTransactionOpts, err := bind.NewTransactor(strings.NewReader(account.Key), account.Password)
	if err != nil {
		err = errors.Errorf("Failed to load key with error: %v", err)
		log.Error(err.Error())
		return nil, err
	} else {
		authedTransactionOpts.GasPrice = config.Config.GetEthereumGasPrice()
		authedTransactionOpts.GasLimit = config.Config.GetEthereumGasLimit()
		return authedTransactionOpts, nil
	}
}

/**
Blocking Function that sends transaction using reflection wrapped in a retrial block. It is based on the TransactionUnderpriced error,
meaning that a transaction is being attempted to run twice, and the logic is to override the existing one. As we have constant
gas prices that means that a concurrent transaction race condition event has happened.
- contractMethod: Contract Method that implements GenericEthereumAsset (usually autogenerated binding from abi)
- params: Arbitrary number of parameters that are passed to the function fname call
*/
func SubmitTransactionWithRetries(contractMethod interface{}, opts *bind.TransactOpts, params ...interface{}) (tx *types.Transaction, err error) {
	done := false
	maxTries := config.Config.GetEthereumMaxRetries()
	current := 0
	var f reflect.Value
	var in []reflect.Value
	var result []reflect.Value
	f = reflect.ValueOf(contractMethod)
	for !done {
		if current >= maxTries {
			log.Error("Max Concurrent transaction tries reached")
			break
		}
		current += 1

		err = IncrementNonce(opts)
		if err != nil {
			return
		}
		in = make([]reflect.Value, len(params)+1)
		val := reflect.ValueOf(opts)
		in[0] = val
		for k, param := range params {
			in[k+1] = reflect.ValueOf(param)
		}
		result = f.Call(in)
		tx = result[0].Interface().(*types.Transaction)
		err = nil
		if result[1].Interface() != nil {
			err = result[1].Interface().(error)
		}

		if err != nil {
			if (err.Error() == TransactionUnderpriced) || (err.Error() == NonceTooLow) {
				log.Warningf("Concurrent transaction identified, trying again [%d/%d]\n", current, maxTries)
				time.Sleep(config.Config.GetEthereumIntervalRetry())
			} else {
				done = true
			}
		} else {
			done = true
		}
	}

	return
}

func IncrementNonce(opts *bind.TransactOpts) (err error) {
	if !config.Config.GetTxPoolAccessEnabled() {
		log.Warningf("Ethereum Client doesn't support txpool API, may cause concurrency issues.")
		return
	}

	gc.GetNonceMutex().Lock()
	defer gc.GetNonceMutex().Unlock()

	var res map[string]map[string]map[string][]string
	// Important to not create a DeadLock if network latency
	txctx, _ := context.WithTimeout(context.Background(), getDefaultContextTimeout())
	gc.GetRpcClient().CallContext(txctx, &res, "txpool_inspect")

	if len(res["pending"][opts.From.Hex()]) > 0 {
		chainNonce, err := gc.GetClient().PendingNonceAt(txctx, opts.From)
		if err != nil {
			log.Errorf("Error found when getting the Account Chain Nonce [%v]\n", err)
			return err
		}
		CalculateIncrement(chainNonce, res, opts)
	}

	return
}

func CalculateIncrement(chainNonce uint64, res map[string]map[string]map[string][]string, opts *bind.TransactOpts) {
	keys := make([]int, 0, len(res["pending"][opts.From.Hex()]))
	for k, _ := range res["pending"][opts.From.Hex()] {
		ki, _ := strconv.Atoi(k)
		keys = append(keys, ki)
	}
	sort.Ints(keys)
	lastPoolNonce := keys[len(keys)-1]
	if uint64(lastPoolNonce) >= chainNonce {
		opts.Nonce = new(big.Int).Add(big.NewInt(int64(lastPoolNonce)), big.NewInt(1))
		log.Infof("Incrementing Nonce to [%v]\n", opts.Nonce.String())
	}
}

func GetGethCallOpts() (auth *bind.CallOpts) {
	// Assuring that pending transactions are taken into account by go-ethereum when asking for things like
	// specific transactions and client's nonce
	return &bind.CallOpts{Pending: true}
}
