// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coredocument.proto

/*
Package coredocument is a generated protocol buffer package.

It is generated from these files:
	coredocument.proto

It has these top-level messages:
	CoreDocument
	Signature
	AccessControlEntry
	AccessControlSchema
	FieldAccess
*/
package coredocument

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CoreDocument is a document that can be sent to different nodes and anchored on chain
type CoreDocument struct {
	// Identifier
	// ----------
	// This is for convenience: the first identifier that was ever used to refer to a
	// document is kept here. Internally the centrifuge node indexes & bundles documents
	// by original identifier.
	DocumentIdentifier []byte `protobuf:"bytes,9,opt,name=document_identifier,json=documentIdentifier,proto3" json:"document_identifier,omitempty"`
	// The current identifier is the location of the current anchor on chain and is used to
	// refer to the current state.
	CurrentIdentifier []byte `protobuf:"bytes,3,opt,name=current_identifier,json=currentIdentifier,proto3" json:"current_identifier,omitempty"`
	// When creating the next version this should be used.
	NextIdentifier []byte `protobuf:"bytes,4,opt,name=next_identifier,json=nextIdentifier,proto3" json:"next_identifier,omitempty"`
	// Root
	PreviousRoot   []byte `protobuf:"bytes,2,opt,name=previous_root,json=previousRoot,proto3" json:"previous_root,omitempty"`
	DataMerkleRoot []byte `protobuf:"bytes,5,opt,name=data_merkle_root,json=dataMerkleRoot,proto3" json:"data_merkle_root,omitempty"`
	DocumentRoot   []byte `protobuf:"bytes,7,opt,name=document_root,json=documentRoot,proto3" json:"document_root,omitempty"`
	// Signatures
	Signatures []*Signature `protobuf:"bytes,6,rep,name=signatures" json:"signatures,omitempty"`
	// List of collaborators on this document. These Centrifuge Identities have access
	// to the document and should receive new versions whenever a document is updated.
	Collaborators [][]byte              `protobuf:"bytes,10,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	Acl           []*AccessControlEntry `protobuf:"bytes,11,rep,name=acl" json:"acl,omitempty"`
	// The previous document is referenced here but doesn't need to be provided and can
	// be left blank
	PreviousVersions []*CoreDocument `protobuf:"bytes,8,rep,name=previous_versions,json=previousVersions" json:"previous_versions,omitempty"`
	// Document a serialized document
	DocumentSchemaId []byte                `protobuf:"bytes,12,opt,name=document_schema_id,json=documentSchemaId,proto3" json:"document_schema_id,omitempty"`
	EmbeddedDocument *google_protobuf1.Any `protobuf:"bytes,13,opt,name=embedded_document,json=embeddedDocument" json:"embedded_document,omitempty"`
}

func (m *CoreDocument) Reset()                    { *m = CoreDocument{} }
func (m *CoreDocument) String() string            { return proto.CompactTextString(m) }
func (*CoreDocument) ProtoMessage()               {}
func (*CoreDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CoreDocument) GetDocumentIdentifier() []byte {
	if m != nil {
		return m.DocumentIdentifier
	}
	return nil
}

func (m *CoreDocument) GetCurrentIdentifier() []byte {
	if m != nil {
		return m.CurrentIdentifier
	}
	return nil
}

func (m *CoreDocument) GetNextIdentifier() []byte {
	if m != nil {
		return m.NextIdentifier
	}
	return nil
}

func (m *CoreDocument) GetPreviousRoot() []byte {
	if m != nil {
		return m.PreviousRoot
	}
	return nil
}

func (m *CoreDocument) GetDataMerkleRoot() []byte {
	if m != nil {
		return m.DataMerkleRoot
	}
	return nil
}

func (m *CoreDocument) GetDocumentRoot() []byte {
	if m != nil {
		return m.DocumentRoot
	}
	return nil
}

func (m *CoreDocument) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *CoreDocument) GetCollaborators() [][]byte {
	if m != nil {
		return m.Collaborators
	}
	return nil
}

func (m *CoreDocument) GetAcl() []*AccessControlEntry {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *CoreDocument) GetPreviousVersions() []*CoreDocument {
	if m != nil {
		return m.PreviousVersions
	}
	return nil
}

func (m *CoreDocument) GetDocumentSchemaId() []byte {
	if m != nil {
		return m.DocumentSchemaId
	}
	return nil
}

func (m *CoreDocument) GetEmbeddedDocument() *google_protobuf1.Any {
	if m != nil {
		return m.EmbeddedDocument
	}
	return nil
}

// Signature contains the entity ID, public key used and signature)
type Signature struct {
	EntityId  []byte `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Signature) GetEntityId() []byte {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *Signature) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// AccessControlEntry defines a member of the document
type AccessControlEntry struct {
	// All identities listed
	Identity [][]byte `protobuf:"bytes,1,rep,name=identity,proto3" json:"identity,omitempty"`
	// There are two ways to describe the acl schema. One of the standard ACL schemas can be referenced by a
	// unique identifier or a schema can be embedded.
	AclSchemaIdentifier []byte               `protobuf:"bytes,2,opt,name=acl_schema_identifier,json=aclSchemaIdentifier,proto3" json:"acl_schema_identifier,omitempty"`
	EmbeddedAclSchema   *AccessControlSchema `protobuf:"bytes,3,opt,name=embedded_acl_schema,json=embeddedAclSchema" json:"embedded_acl_schema,omitempty"`
}

func (m *AccessControlEntry) Reset()                    { *m = AccessControlEntry{} }
func (m *AccessControlEntry) String() string            { return proto.CompactTextString(m) }
func (*AccessControlEntry) ProtoMessage()               {}
func (*AccessControlEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccessControlEntry) GetIdentity() [][]byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *AccessControlEntry) GetAclSchemaIdentifier() []byte {
	if m != nil {
		return m.AclSchemaIdentifier
	}
	return nil
}

func (m *AccessControlEntry) GetEmbeddedAclSchema() *AccessControlSchema {
	if m != nil {
		return m.EmbeddedAclSchema
	}
	return nil
}

type AccessControlSchema struct {
	// Set either to true to grant access to also look at past versions of the document and/or future updates
	// to the document.
	GrantPastVersionAccess           bool                        `protobuf:"varint,2,opt,name=grant_past_version_access,json=grantPastVersionAccess" json:"grant_past_version_access,omitempty"`
	GrantFutureVersionAccess         bool                        `protobuf:"varint,3,opt,name=grant_future_version_access,json=grantFutureVersionAccess" json:"grant_future_version_access,omitempty"`
	GrantAccessToFutureVersionsUntil *google_protobuf2.Timestamp `protobuf:"bytes,4,opt,name=grant_access_to_future_versions_until,json=grantAccessToFutureVersionsUntil" json:"grant_access_to_future_versions_until,omitempty"`
	// TODO: how granular do we want to grant these permissions? Fields?
	ReadFields  []*FieldAccess `protobuf:"bytes,5,rep,name=read_fields,json=readFields" json:"read_fields,omitempty"`
	WriteFields []*FieldAccess `protobuf:"bytes,6,rep,name=write_fields,json=writeFields" json:"write_fields,omitempty"`
}

func (m *AccessControlSchema) Reset()                    { *m = AccessControlSchema{} }
func (m *AccessControlSchema) String() string            { return proto.CompactTextString(m) }
func (*AccessControlSchema) ProtoMessage()               {}
func (*AccessControlSchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AccessControlSchema) GetGrantPastVersionAccess() bool {
	if m != nil {
		return m.GrantPastVersionAccess
	}
	return false
}

func (m *AccessControlSchema) GetGrantFutureVersionAccess() bool {
	if m != nil {
		return m.GrantFutureVersionAccess
	}
	return false
}

func (m *AccessControlSchema) GetGrantAccessToFutureVersionsUntil() *google_protobuf2.Timestamp {
	if m != nil {
		return m.GrantAccessToFutureVersionsUntil
	}
	return nil
}

func (m *AccessControlSchema) GetReadFields() []*FieldAccess {
	if m != nil {
		return m.ReadFields
	}
	return nil
}

func (m *AccessControlSchema) GetWriteFields() []*FieldAccess {
	if m != nil {
		return m.WriteFields
	}
	return nil
}

type FieldAccess struct {
	// TODO: how do we identify field names?
	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
}

func (m *FieldAccess) Reset()                    { *m = FieldAccess{} }
func (m *FieldAccess) String() string            { return proto.CompactTextString(m) }
func (*FieldAccess) ProtoMessage()               {}
func (*FieldAccess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FieldAccess) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func init() {
	proto.RegisterType((*CoreDocument)(nil), "coredocument.CoreDocument")
	proto.RegisterType((*Signature)(nil), "coredocument.Signature")
	proto.RegisterType((*AccessControlEntry)(nil), "coredocument.AccessControlEntry")
	proto.RegisterType((*AccessControlSchema)(nil), "coredocument.AccessControlSchema")
	proto.RegisterType((*FieldAccess)(nil), "coredocument.FieldAccess")
}

func init() { proto.RegisterFile("coredocument.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdf, 0x6e, 0xe2, 0x46,
	0x14, 0xc6, 0x45, 0x48, 0x52, 0x38, 0x40, 0x4b, 0x86, 0xfe, 0x71, 0x48, 0xaa, 0x52, 0xd2, 0xaa,
	0x5c, 0x04, 0x2c, 0xd1, 0x8b, 0xaa, 0x55, 0x5b, 0x95, 0xa6, 0x4d, 0x85, 0xaa, 0x5d, 0xed, 0x3a,
	0xd9, 0xbd, 0xd8, 0x1b, 0x6b, 0xb0, 0x07, 0xc7, 0x8a, 0x3d, 0x83, 0x66, 0xc6, 0xc9, 0xf2, 0x64,
	0xfb, 0x2a, 0xfb, 0x24, 0x7b, 0xbd, 0xf2, 0x19, 0x8f, 0x63, 0x93, 0xd5, 0xee, 0x15, 0xf8, 0x3b,
	0xbf, 0xf3, 0xcd, 0xf0, 0x9d, 0x83, 0x81, 0x04, 0x42, 0xb2, 0x50, 0x04, 0x59, 0xca, 0xb8, 0x9e,
	0x6d, 0xa4, 0xd0, 0x82, 0x74, 0xab, 0xda, 0xf0, 0x34, 0x12, 0x22, 0x4a, 0x98, 0x4b, 0x37, 0xb1,
	0x4b, 0x39, 0x17, 0x9a, 0xea, 0x58, 0x70, 0x65, 0xd8, 0xe1, 0x71, 0x51, 0xc5, 0xa7, 0x55, 0xb6,
	0x76, 0x29, 0xdf, 0x16, 0xa5, 0xef, 0x76, 0x4b, 0x3a, 0x4e, 0x99, 0xd2, 0x34, 0xdd, 0x14, 0xc0,
	0x39, 0x7e, 0x04, 0xd3, 0x88, 0xf1, 0xa9, 0xba, 0xa7, 0x51, 0xc4, 0xa4, 0x2b, 0x36, 0xe8, 0xfe,
	0xf8, 0xa4, 0xf1, 0xdb, 0x7d, 0xe8, 0x5e, 0x08, 0xc9, 0xfe, 0x29, 0x2e, 0x46, 0x5c, 0x18, 0xd8,
	0x4b, 0xfa, 0x71, 0xc8, 0xb8, 0x8e, 0xd7, 0x31, 0x93, 0x4e, 0x7b, 0xd4, 0x98, 0x74, 0x3d, 0x62,
	0x4b, 0xcb, 0xb2, 0x42, 0xa6, 0x40, 0x82, 0x4c, 0xca, 0x1d, 0xbe, 0x89, 0xfc, 0x51, 0x51, 0xa9,
	0xe0, 0x3f, 0xc1, 0x17, 0x9c, 0xbd, 0xae, 0xb1, 0xfb, 0xc8, 0x7e, 0x9e, 0xcb, 0x15, 0xf0, 0x0c,
	0x7a, 0x1b, 0xc9, 0xee, 0x62, 0x91, 0x29, 0x5f, 0x0a, 0xa1, 0x9d, 0x3d, 0xc4, 0xba, 0x56, 0xf4,
	0x84, 0xd0, 0x64, 0x02, 0xfd, 0x90, 0x6a, 0xea, 0xa7, 0x4c, 0xde, 0x26, 0xcc, 0x70, 0x07, 0xc6,
	0x2e, 0xd7, 0x9f, 0xa0, 0x8c, 0xe4, 0x19, 0xf4, 0xca, 0xdf, 0x85, 0xd8, 0x67, 0xc6, 0xce, 0x8a,
	0x08, 0xfd, 0x02, 0xa0, 0xe2, 0x88, 0x53, 0x9d, 0x49, 0xa6, 0x9c, 0xc3, 0x51, 0x73, 0xd2, 0x99,
	0x7f, 0x33, 0xab, 0x0d, 0xf3, 0xca, 0xd6, 0xbd, 0x0a, 0x4a, 0x7e, 0x80, 0x5e, 0x20, 0x92, 0x84,
	0xae, 0x84, 0xa4, 0x5a, 0x48, 0xe5, 0xc0, 0xa8, 0x39, 0xe9, 0x7a, 0x75, 0x91, 0xcc, 0xa1, 0x49,
	0x83, 0xc4, 0xe9, 0xa0, 0xef, 0xa8, 0xee, 0xbb, 0x08, 0x02, 0xa6, 0xd4, 0x85, 0xe0, 0x5a, 0x8a,
	0xe4, 0x5f, 0xae, 0xe5, 0xd6, 0xcb, 0x61, 0xf2, 0x1f, 0x1c, 0x95, 0x31, 0xdc, 0x31, 0xa9, 0xf2,
	0xd9, 0x39, 0x2d, 0x74, 0x18, 0xd6, 0x1d, 0xaa, 0x63, 0xf4, 0xfa, 0xb6, 0xe9, 0x65, 0xd1, 0x43,
	0xce, 0xa1, 0x9c, 0x9e, 0xaf, 0x82, 0x1b, 0x96, 0x52, 0x3f, 0x0e, 0x9d, 0x2e, 0xa6, 0xd0, 0xb7,
	0x95, 0x2b, 0x2c, 0x2c, 0x43, 0xb2, 0x80, 0x23, 0x96, 0xae, 0x58, 0x18, 0xb2, 0xd0, 0xb7, 0x45,
	0xa7, 0x37, 0x6a, 0x4c, 0x3a, 0xf3, 0x2f, 0x67, 0x66, 0x05, 0x67, 0x76, 0x05, 0x67, 0x0b, 0xbe,
	0xf5, 0xfa, 0x16, 0xb7, 0x57, 0x18, 0x33, 0x68, 0x97, 0x61, 0x91, 0x13, 0x68, 0xe7, 0x93, 0xd5,
	0xdb, 0xfc, 0xd0, 0x06, 0x1e, 0xda, 0x32, 0xc2, 0x32, 0x24, 0xdf, 0x02, 0x6c, 0xb2, 0x55, 0x12,
	0x07, 0xfe, 0x2d, 0xdb, 0x16, 0x73, 0x6e, 0x1b, 0xe5, 0x7f, 0xb6, 0x25, 0xa7, 0xd0, 0x2e, 0xa3,
	0x2e, 0x16, 0xeb, 0x41, 0x18, 0xbf, 0x69, 0x00, 0x79, 0x1c, 0x1e, 0x19, 0x42, 0xcb, 0xac, 0x98,
	0xde, 0x3a, 0x0d, 0x1c, 0x46, 0xf9, 0x4c, 0xe6, 0xf0, 0x15, 0x0d, 0x92, 0x87, 0x14, 0xca, 0x4d,
	0x34, 0x47, 0x0f, 0x68, 0x90, 0xd8, 0x20, 0xca, 0x75, 0x7c, 0x0e, 0x83, 0x32, 0x90, 0x87, 0x66,
	0xbc, 0x4e, 0x67, 0xfe, 0xfd, 0x47, 0x66, 0x69, 0x9c, 0xbc, 0x32, 0xce, 0x85, 0x35, 0x1f, 0xbf,
	0xdb, 0x83, 0xc1, 0x07, 0x50, 0xf2, 0x2b, 0x1c, 0x47, 0x92, 0x72, 0xed, 0x6f, 0xa8, 0xd2, 0x76,
	0xe8, 0x3e, 0x45, 0x12, 0xaf, 0xd8, 0xf2, 0xbe, 0x46, 0xe0, 0x19, 0x55, 0xba, 0x98, 0xaf, 0xf1,
	0x21, 0x7f, 0xc0, 0x89, 0x69, 0x5d, 0x67, 0x79, 0x38, 0xbb, 0xcd, 0x4d, 0x6c, 0x76, 0x10, 0xb9,
	0x44, 0xa2, 0xde, 0x7e, 0x0b, 0x3f, 0x9a, 0x76, 0xc3, 0xfb, 0x5a, 0xec, 0x18, 0x29, 0x3f, 0xe3,
	0x3a, 0x4e, 0xf0, 0x2f, 0x9b, 0x2f, 0xe0, 0xee, 0x26, 0x5c, 0xdb, 0x97, 0x91, 0x37, 0x42, 0x23,
	0xe3, 0x7b, 0x2d, 0x6a, 0x87, 0xa9, 0x17, 0xb9, 0x07, 0xf9, 0x0d, 0x3a, 0x92, 0xd1, 0xd0, 0x5f,
	0xc7, 0x2c, 0x09, 0x95, 0x73, 0x80, 0x3b, 0x7d, 0x5c, 0x4f, 0xf2, 0x32, 0xaf, 0x19, 0x13, 0x0f,
	0x72, 0x1a, 0x05, 0x45, 0x7e, 0x87, 0xee, 0xbd, 0x8c, 0x35, 0xb3, 0xcd, 0x87, 0x9f, 0x6a, 0xee,
	0x20, 0x6e, 0xba, 0xc7, 0xe7, 0xd0, 0xa9, 0xd4, 0xf2, 0xf5, 0x43, 0x1b, 0x9f, 0xd3, 0x94, 0xe1,
	0x72, 0xb6, 0xbd, 0x36, 0x2a, 0x4f, 0x69, 0xca, 0xfe, 0xfe, 0xeb, 0xd5, 0x9f, 0x51, 0xac, 0x6f,
	0xb2, 0xd5, 0x2c, 0x10, 0xa9, 0x7b, 0xc1, 0xb8, 0x96, 0xf1, 0x3a, 0x8b, 0xd8, 0x92, 0x07, 0x6e,
	0x24, 0xa6, 0x41, 0x29, 0xb8, 0xd5, 0xaf, 0x95, 0x8b, 0xac, 0x0e, 0x31, 0x9f, 0x9f, 0xdf, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x4b, 0xaa, 0x72, 0x17, 0x06, 0x00, 0x00,
}
