// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coredocument/grpc/coredocument_grpc.proto

/*
Package coredocumentgrpc is a generated protocol buffer package.

It is generated from these files:
	coredocument/grpc/coredocument_grpc.proto

It has these top-level messages:
	P2PMessage
	P2PReply
*/
package coredocumentgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import coredocument "github.com/CentrifugeInc/centrifuge-protobufs/coredocument"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// P2PMessage wraps a single CoreDocument to be transferred to another noed
type P2PMessage struct {
	Document *coredocument.CoreDocument `protobuf:"bytes,1,opt,name=document" json:"document,omitempty"`
}

func (m *P2PMessage) Reset()                    { *m = P2PMessage{} }
func (m *P2PMessage) String() string            { return proto.CompactTextString(m) }
func (*P2PMessage) ProtoMessage()               {}
func (*P2PMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *P2PMessage) GetDocument() *coredocument.CoreDocument {
	if m != nil {
		return m.Document
	}
	return nil
}

type P2PReply struct {
	Document *coredocument.CoreDocument `protobuf:"bytes,1,opt,name=document" json:"document,omitempty"`
}

func (m *P2PReply) Reset()                    { *m = P2PReply{} }
func (m *P2PReply) String() string            { return proto.CompactTextString(m) }
func (*P2PReply) ProtoMessage()               {}
func (*P2PReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *P2PReply) GetDocument() *coredocument.CoreDocument {
	if m != nil {
		return m.Document
	}
	return nil
}

func init() {
	proto.RegisterType((*P2PMessage)(nil), "coredocumentgrpc.P2PMessage")
	proto.RegisterType((*P2PReply)(nil), "coredocumentgrpc.P2PReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for P2PService service

type P2PServiceClient interface {
	Post(ctx context.Context, in *P2PMessage, opts ...grpc.CallOption) (*P2PReply, error)
}

type p2PServiceClient struct {
	cc *grpc.ClientConn
}

func NewP2PServiceClient(cc *grpc.ClientConn) P2PServiceClient {
	return &p2PServiceClient{cc}
}

func (c *p2PServiceClient) Post(ctx context.Context, in *P2PMessage, opts ...grpc.CallOption) (*P2PReply, error) {
	out := new(P2PReply)
	err := grpc.Invoke(ctx, "/coredocumentgrpc.P2PService/Post", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for P2PService service

type P2PServiceServer interface {
	Post(context.Context, *P2PMessage) (*P2PReply, error)
}

func RegisterP2PServiceServer(s *grpc.Server, srv P2PServiceServer) {
	s.RegisterService(&_P2PService_serviceDesc, srv)
}

func _P2PService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(P2PMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coredocumentgrpc.P2PService/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PServiceServer).Post(ctx, req.(*P2PMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _P2PService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coredocumentgrpc.P2PService",
	HandlerType: (*P2PServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _P2PService_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coredocument/grpc/coredocument_grpc.proto",
}

func init() { proto.RegisterFile("coredocument/grpc/coredocument_grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0xce, 0x2f, 0x4a,
	0x4d, 0xc9, 0x4f, 0x2e, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x47, 0x16,
	0x89, 0x07, 0x89, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x09, 0x20, 0x4b, 0x80, 0xc4, 0xa5,
	0x4c, 0x92, 0x53, 0xf3, 0x4a, 0x8a, 0x32, 0xd3, 0x4a, 0xd3, 0x53, 0x75, 0xc1, 0x6a, 0x92, 0x4a,
	0xd3, 0x8a, 0x51, 0xf4, 0xa3, 0x70, 0x20, 0xe6, 0x28, 0xb9, 0x70, 0x71, 0x05, 0x18, 0x05, 0xf8,
	0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x99, 0x71, 0x71, 0xc0, 0xe4, 0x25, 0x18, 0x15, 0x18,
	0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x50, 0x34, 0x39, 0xe7, 0x17, 0xa5, 0xba, 0x40, 0x39, 0x41, 0x70,
	0xb5, 0x4a, 0x4e, 0x5c, 0x1c, 0x01, 0x46, 0x01, 0x41, 0xa9, 0x05, 0x39, 0x95, 0xe4, 0x9a, 0x61,
	0x14, 0x00, 0x76, 0x49, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x13, 0x17, 0x4b, 0x40,
	0x7e, 0x71, 0x89, 0x90, 0x8c, 0x1e, 0xba, 0x47, 0xf5, 0x10, 0xee, 0x95, 0x92, 0xc2, 0x2a, 0x0b,
	0x76, 0x87, 0x12, 0x83, 0x93, 0x50, 0x14, 0x46, 0x28, 0x25, 0xb1, 0x81, 0xbd, 0x6d, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0xf1, 0x36, 0x1a, 0x6b, 0x01, 0x00, 0x00,
}
