// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoice/invoice.proto

/*
Package invoice is a generated protocol buffer package.

It is generated from these files:
	invoice/invoice.proto

It has these top-level messages:
	InvoiceDocument
	SendInvoiceEnvelope
	GetInvoiceDocumentEnvelope
	ReceivedInvoices
	Empty
*/
package invoice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import coredocument "github.com/CentrifugeInc/go-centrifuge/centrifuge/coredocument"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// InvoiceDocument is a Centrifuge enabled document that can be used to represent
type InvoiceDocument struct {
	// documentIdentifier
	DocumentIdentifier []byte `protobuf:"bytes,3,opt,name=documentIdentifier,proto3" json:"documentIdentifier,omitempty"`
	// CoreDocument contains data related to the Centrifuge OS layer
	CoreDocument *coredocument.CoreDocument `protobuf:"bytes,1,opt,name=coreDocument" json:"coreDocument,omitempty"`
	// InvoiceData has all invoice specific information.
	Data *InvoiceDocument_InvoiceData `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *InvoiceDocument) Reset()                    { *m = InvoiceDocument{} }
func (m *InvoiceDocument) String() string            { return proto.CompactTextString(m) }
func (*InvoiceDocument) ProtoMessage()               {}
func (*InvoiceDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InvoiceDocument) GetDocumentIdentifier() []byte {
	if m != nil {
		return m.DocumentIdentifier
	}
	return nil
}

func (m *InvoiceDocument) GetCoreDocument() *coredocument.CoreDocument {
	if m != nil {
		return m.CoreDocument
	}
	return nil
}

func (m *InvoiceDocument) GetData() *InvoiceDocument_InvoiceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type InvoiceDocument_InvoiceData struct {
	Country     string                      `protobuf:"bytes,2,opt,name=country" json:"country,omitempty"`
	Currency    string                      `protobuf:"bytes,3,opt,name=currency" json:"currency,omitempty"`
	Amount      int64                       `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Recipient   []byte                      `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sender      []byte                      `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Payee       []byte                      `protobuf:"bytes,7,opt,name=payee,proto3" json:"payee,omitempty"`
	Comment     string                      `protobuf:"bytes,8,opt,name=comment" json:"comment,omitempty"`
	DueDate     *google_protobuf1.Timestamp `protobuf:"bytes,9,opt,name=dueDate" json:"dueDate,omitempty"`
	DateCreated *google_protobuf1.Timestamp `protobuf:"bytes,11,opt,name=dateCreated" json:"dateCreated,omitempty"`
}

func (m *InvoiceDocument_InvoiceData) Reset()                    { *m = InvoiceDocument_InvoiceData{} }
func (m *InvoiceDocument_InvoiceData) String() string            { return proto.CompactTextString(m) }
func (*InvoiceDocument_InvoiceData) ProtoMessage()               {}
func (*InvoiceDocument_InvoiceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *InvoiceDocument_InvoiceData) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *InvoiceDocument_InvoiceData) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *InvoiceDocument_InvoiceData) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InvoiceDocument_InvoiceData) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *InvoiceDocument_InvoiceData) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *InvoiceDocument_InvoiceData) GetPayee() []byte {
	if m != nil {
		return m.Payee
	}
	return nil
}

func (m *InvoiceDocument_InvoiceData) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *InvoiceDocument_InvoiceData) GetDueDate() *google_protobuf1.Timestamp {
	if m != nil {
		return m.DueDate
	}
	return nil
}

func (m *InvoiceDocument_InvoiceData) GetDateCreated() *google_protobuf1.Timestamp {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

type SendInvoiceEnvelope struct {
	// Centrifuge OS Entity of the recipient
	Recipients [][]byte         `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Document   *InvoiceDocument `protobuf:"bytes,10,opt,name=document" json:"document,omitempty"`
}

func (m *SendInvoiceEnvelope) Reset()                    { *m = SendInvoiceEnvelope{} }
func (m *SendInvoiceEnvelope) String() string            { return proto.CompactTextString(m) }
func (*SendInvoiceEnvelope) ProtoMessage()               {}
func (*SendInvoiceEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendInvoiceEnvelope) GetRecipients() [][]byte {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *SendInvoiceEnvelope) GetDocument() *InvoiceDocument {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetInvoiceDocumentEnvelope struct {
	DocumentIdentifier []byte `protobuf:"bytes,1,opt,name=documentIdentifier,proto3" json:"documentIdentifier,omitempty"`
}

func (m *GetInvoiceDocumentEnvelope) Reset()                    { *m = GetInvoiceDocumentEnvelope{} }
func (m *GetInvoiceDocumentEnvelope) String() string            { return proto.CompactTextString(m) }
func (*GetInvoiceDocumentEnvelope) ProtoMessage()               {}
func (*GetInvoiceDocumentEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetInvoiceDocumentEnvelope) GetDocumentIdentifier() []byte {
	if m != nil {
		return m.DocumentIdentifier
	}
	return nil
}

type ReceivedInvoices struct {
	Invoices [][]byte `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
}

func (m *ReceivedInvoices) Reset()                    { *m = ReceivedInvoices{} }
func (m *ReceivedInvoices) String() string            { return proto.CompactTextString(m) }
func (*ReceivedInvoices) ProtoMessage()               {}
func (*ReceivedInvoices) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReceivedInvoices) GetInvoices() [][]byte {
	if m != nil {
		return m.Invoices
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*InvoiceDocument)(nil), "invoice.InvoiceDocument")
	proto.RegisterType((*InvoiceDocument_InvoiceData)(nil), "invoice.InvoiceDocument.InvoiceData")
	proto.RegisterType((*SendInvoiceEnvelope)(nil), "invoice.SendInvoiceEnvelope")
	proto.RegisterType((*GetInvoiceDocumentEnvelope)(nil), "invoice.GetInvoiceDocumentEnvelope")
	proto.RegisterType((*ReceivedInvoices)(nil), "invoice.ReceivedInvoices")
	proto.RegisterType((*Empty)(nil), "invoice.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for InvoiceDocumentService service

type InvoiceDocumentServiceClient interface {
	// Anchors a document on chain. Returns updated document with signatures and root calculated.
	AnchorDocument(ctx context.Context, in *InvoiceDocument, opts ...grpc.CallOption) (*InvoiceDocument, error)
	SendInvoiceDocument(ctx context.Context, in *SendInvoiceEnvelope, opts ...grpc.CallOption) (*InvoiceDocument, error)
	GetInvoiceDocument(ctx context.Context, in *GetInvoiceDocumentEnvelope, opts ...grpc.CallOption) (*InvoiceDocument, error)
	GetReceivedInvoiceDocuments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReceivedInvoices, error)
}

type invoiceDocumentServiceClient struct {
	cc *grpc.ClientConn
}

func NewInvoiceDocumentServiceClient(cc *grpc.ClientConn) InvoiceDocumentServiceClient {
	return &invoiceDocumentServiceClient{cc}
}

func (c *invoiceDocumentServiceClient) AnchorDocument(ctx context.Context, in *InvoiceDocument, opts ...grpc.CallOption) (*InvoiceDocument, error) {
	out := new(InvoiceDocument)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/AnchorDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceDocumentServiceClient) SendInvoiceDocument(ctx context.Context, in *SendInvoiceEnvelope, opts ...grpc.CallOption) (*InvoiceDocument, error) {
	out := new(InvoiceDocument)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/SendInvoiceDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceDocumentServiceClient) GetInvoiceDocument(ctx context.Context, in *GetInvoiceDocumentEnvelope, opts ...grpc.CallOption) (*InvoiceDocument, error) {
	out := new(InvoiceDocument)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/GetInvoiceDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceDocumentServiceClient) GetReceivedInvoiceDocuments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReceivedInvoices, error) {
	out := new(ReceivedInvoices)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/GetReceivedInvoiceDocuments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InvoiceDocumentService service

type InvoiceDocumentServiceServer interface {
	// Anchors a document on chain. Returns updated document with signatures and root calculated.
	AnchorDocument(context.Context, *InvoiceDocument) (*InvoiceDocument, error)
	SendInvoiceDocument(context.Context, *SendInvoiceEnvelope) (*InvoiceDocument, error)
	GetInvoiceDocument(context.Context, *GetInvoiceDocumentEnvelope) (*InvoiceDocument, error)
	GetReceivedInvoiceDocuments(context.Context, *Empty) (*ReceivedInvoices, error)
}

func RegisterInvoiceDocumentServiceServer(s *grpc.Server, srv InvoiceDocumentServiceServer) {
	s.RegisterService(&_InvoiceDocumentService_serviceDesc, srv)
}

func _InvoiceDocumentService_AnchorDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvoiceDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).AnchorDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/AnchorDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).AnchorDocument(ctx, req.(*InvoiceDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceDocumentService_SendInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInvoiceEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).SendInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/SendInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).SendInvoiceDocument(ctx, req.(*SendInvoiceEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceDocumentService_GetInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceDocumentEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).GetInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/GetInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).GetInvoiceDocument(ctx, req.(*GetInvoiceDocumentEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceDocumentService_GetReceivedInvoiceDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).GetReceivedInvoiceDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/GetReceivedInvoiceDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).GetReceivedInvoiceDocuments(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _InvoiceDocumentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.InvoiceDocumentService",
	HandlerType: (*InvoiceDocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnchorDocument",
			Handler:    _InvoiceDocumentService_AnchorDocument_Handler,
		},
		{
			MethodName: "SendInvoiceDocument",
			Handler:    _InvoiceDocumentService_SendInvoiceDocument_Handler,
		},
		{
			MethodName: "GetInvoiceDocument",
			Handler:    _InvoiceDocumentService_GetInvoiceDocument_Handler,
		},
		{
			MethodName: "GetReceivedInvoiceDocuments",
			Handler:    _InvoiceDocumentService_GetReceivedInvoiceDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/invoice.proto",
}

func init() { proto.RegisterFile("invoice/invoice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6e, 0xd3, 0x40,
	0x14, 0x96, 0x93, 0xa6, 0x69, 0x26, 0xa5, 0xad, 0x86, 0x50, 0x19, 0x13, 0x81, 0x71, 0x59, 0x84,
	0x8a, 0xda, 0x25, 0x74, 0x51, 0x22, 0x84, 0x28, 0x69, 0x55, 0x45, 0x42, 0x02, 0xb9, 0xac, 0x58,
	0x31, 0x1d, 0xbf, 0x38, 0x06, 0x67, 0xc6, 0xb2, 0x27, 0x41, 0x11, 0x82, 0x05, 0x47, 0x80, 0x0b,
	0x70, 0x09, 0x4e, 0xc1, 0x92, 0x03, 0xb0, 0xe1, 0x06, 0x5c, 0x00, 0x79, 0x62, 0x4f, 0xdc, 0x34,
	0x29, 0x2b, 0xe7, 0x7b, 0xef, 0x7b, 0xef, 0x7b, 0x7f, 0x13, 0x74, 0x23, 0x60, 0x63, 0x1e, 0x50,
	0x70, 0xb2, 0xaf, 0x1d, 0xc5, 0x5c, 0x70, 0x5c, 0xcd, 0xa0, 0xd1, 0xf4, 0x39, 0xf7, 0x43, 0x70,
	0x48, 0x14, 0x38, 0x84, 0x31, 0x2e, 0x88, 0x08, 0x38, 0x4b, 0xa6, 0x34, 0xe3, 0x4e, 0xe6, 0x95,
	0xe8, 0x7c, 0xd4, 0x77, 0x44, 0x30, 0x84, 0x44, 0x90, 0x61, 0x94, 0x11, 0x1e, 0xc8, 0x0f, 0xdd,
	0xf3, 0x81, 0xed, 0x25, 0x1f, 0x88, 0xef, 0x43, 0xec, 0xf0, 0x48, 0xa6, 0x58, 0x94, 0x8e, 0xf2,
	0x18, 0x3c, 0x4e, 0x47, 0x43, 0x60, 0xc2, 0x29, 0x82, 0x29, 0xc1, 0xfa, 0x5b, 0x46, 0x9b, 0xbd,
	0x69, 0x65, 0xc7, 0x99, 0x07, 0xdb, 0x08, 0xe7, 0xac, 0x9e, 0x07, 0x4c, 0x04, 0xfd, 0x00, 0x62,
	0xbd, 0x6c, 0x6a, 0xad, 0x75, 0x77, 0x81, 0x07, 0x3f, 0x45, 0xeb, 0x69, 0xe6, 0x3c, 0x5e, 0xd7,
	0x4c, 0xad, 0x55, 0x6f, 0x1b, 0xf6, 0x05, 0xb9, 0x6e, 0x81, 0xe1, 0x5e, 0xe0, 0xe3, 0x43, 0xb4,
	0xe2, 0x11, 0x41, 0xf4, 0x92, 0x8c, 0xbb, 0x67, 0xe7, 0x83, 0x9b, 0xab, 0x4b, 0x61, 0x22, 0x88,
	0x2b, 0x23, 0x8c, 0x1f, 0x25, 0x54, 0x2f, 0x58, 0xb1, 0x8e, 0xaa, 0x94, 0x8f, 0x98, 0x88, 0x27,
	0x32, 0x59, 0xcd, 0xcd, 0x21, 0x36, 0xd0, 0x1a, 0x1d, 0xc5, 0x31, 0x30, 0x3a, 0x91, 0x9d, 0xd4,
	0x5c, 0x85, 0xf1, 0x36, 0x5a, 0x25, 0xc3, 0x94, 0xa7, 0xaf, 0x98, 0x5a, 0xab, 0xec, 0x66, 0x08,
	0x37, 0x51, 0x2d, 0x06, 0x1a, 0x44, 0x41, 0xda, 0x54, 0x45, 0xb6, 0x3f, 0x33, 0xa4, 0x51, 0x09,
	0x30, 0x0f, 0x62, 0x7d, 0x55, 0xba, 0x32, 0x84, 0x1b, 0xa8, 0x12, 0x91, 0x09, 0x80, 0x5e, 0x95,
	0xe6, 0x29, 0x98, 0x56, 0x36, 0x94, 0xe3, 0x59, 0xcb, 0x2b, 0x93, 0x10, 0x1f, 0xa0, 0xaa, 0x37,
	0x4a, 0xcb, 0x07, 0xbd, 0x96, 0x0d, 0x6e, 0x7a, 0x03, 0x76, 0x7e, 0x03, 0xf6, 0xeb, 0xfc, 0x06,
	0xdc, 0x9c, 0x8a, 0x9f, 0xa0, 0xba, 0x47, 0x04, 0x74, 0x63, 0x20, 0x02, 0x3c, 0xbd, 0xfe, 0xdf,
	0xc8, 0x22, 0xdd, 0x7a, 0x8f, 0xae, 0x9f, 0x01, 0xf3, 0xb2, 0xd1, 0x9d, 0xb0, 0x31, 0x84, 0x3c,
	0x02, 0x7c, 0x1b, 0x21, 0xd5, 0x5f, 0xa2, 0x6b, 0x66, 0xb9, 0xb5, 0xee, 0x16, 0x2c, 0xf8, 0x00,
	0xad, 0xe5, 0xfb, 0xd4, 0x91, 0x54, 0xd4, 0x97, 0x2d, 0xcb, 0x55, 0x4c, 0xeb, 0x05, 0x32, 0x4e,
	0x41, 0xcc, 0xf9, 0x95, 0xe6, 0xe2, 0x63, 0xd3, 0x96, 0x1d, 0x9b, 0x65, 0xa3, 0x2d, 0x17, 0x28,
	0x04, 0x63, 0xc8, 0xcb, 0x4f, 0xd2, 0xe5, 0x66, 0x65, 0xe4, 0x55, 0x2b, 0x6c, 0x55, 0x51, 0xe5,
	0x64, 0x18, 0x89, 0x49, 0xfb, 0x67, 0x19, 0x6d, 0xcf, 0x15, 0x71, 0x06, 0xf1, 0x38, 0xa0, 0x80,
	0xdf, 0xa2, 0x8d, 0x23, 0x46, 0x07, 0x3c, 0x56, 0x27, 0xb9, 0xb4, 0x2f, 0x63, 0xa9, 0xc7, 0x32,
	0xbe, 0xfc, 0xfa, 0xf3, 0xad, 0xd4, 0xb0, 0x36, 0xf3, 0x97, 0xef, 0x10, 0x99, 0xb4, 0xa3, 0xed,
	0x62, 0xff, 0xc2, 0xc0, 0x95, 0x4c, 0x53, 0x25, 0x5b, 0xb0, 0x8e, 0x2b, 0xa4, 0x74, 0x29, 0x85,
	0xad, 0x6b, 0x4a, 0x2a, 0x3d, 0xbe, 0x54, 0xe8, 0x33, 0xc2, 0x97, 0x87, 0x8d, 0x77, 0x54, 0xa6,
	0xe5, 0x9b, 0xb8, 0x42, 0xee, 0xbe, 0x94, 0xdb, 0xc1, 0x77, 0x95, 0x9c, 0x0f, 0xc2, 0xf9, 0x78,
	0x79, 0x3b, 0x9f, 0x70, 0x1f, 0xdd, 0x3a, 0x05, 0x31, 0xb7, 0xa1, 0x3c, 0x51, 0x82, 0x37, 0x94,
	0x86, 0x5c, 0x8a, 0x71, 0x53, 0xe1, 0xf9, 0xa5, 0x5a, 0x4d, 0x29, 0xba, 0x8d, 0x1b, 0x45, 0xd1,
	0x9c, 0xf5, 0xfc, 0xb7, 0xf6, 0xf5, 0xe8, 0xbb, 0x86, 0x7d, 0xa4, 0x77, 0x81, 0x89, 0x38, 0xe8,
	0x8f, 0x7c, 0x30, 0x5f, 0x9e, 0x99, 0xdd, 0x30, 0x3d, 0x55, 0xf3, 0xe8, 0x55, 0xcf, 0x3a, 0x46,
	0x68, 0xe6, 0xc3, 0xe6, 0x40, 0x88, 0x28, 0xe9, 0x38, 0x8e, 0x1f, 0x88, 0xc1, 0xe8, 0xdc, 0xa6,
	0x7c, 0xe8, 0xcc, 0xdc, 0x3d, 0x46, 0x8d, 0xc6, 0x00, 0xc2, 0x90, 0x3f, 0xa3, 0xca, 0x68, 0x73,
	0x06, 0xed, 0xca, 0xbe, 0xbd, 0x6f, 0x3f, 0x34, 0x36, 0x42, 0x4e, 0x49, 0x38, 0xe0, 0x89, 0xe8,
	0x1c, 0xee, 0x1f, 0xb6, 0x77, 0xb5, 0x52, 0x7b, 0x8b, 0x44, 0x51, 0x18, 0x50, 0xf9, 0x7f, 0xeb,
	0xbc, 0x4b, 0x38, 0xeb, 0x5c, 0xb2, 0xbc, 0x79, 0xbc, 0x4c, 0xcd, 0xf1, 0xf9, 0xde, 0x4c, 0xc9,
	0x29, 0xfc, 0xcc, 0xba, 0x3d, 0x5f, 0x95, 0x8f, 0xf8, 0xd1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5a, 0x68, 0xf8, 0xc7, 0x50, 0x06, 0x00, 0x00,
}
