// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoice/invoice.proto

/*
Package invoice is a generated protocol buffer package.

It is generated from these files:
	invoice/invoice.proto

It has these top-level messages:
	SendInvoiceEnvelope
	GetInvoiceDocumentEnvelope
	ReceivedInvoices
*/
package invoice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import invoice1 "github.com/CentrifugeInc/centrifuge-protobufs/invoice"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendInvoiceEnvelope struct {
	// Centrifuge OS Entity of the recipient
	Recipients [][]byte                  `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Document   *invoice1.InvoiceDocument `protobuf:"bytes,10,opt,name=document" json:"document,omitempty"`
}

func (m *SendInvoiceEnvelope) Reset()                    { *m = SendInvoiceEnvelope{} }
func (m *SendInvoiceEnvelope) String() string            { return proto.CompactTextString(m) }
func (*SendInvoiceEnvelope) ProtoMessage()               {}
func (*SendInvoiceEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendInvoiceEnvelope) GetRecipients() [][]byte {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *SendInvoiceEnvelope) GetDocument() *invoice1.InvoiceDocument {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetInvoiceDocumentEnvelope struct {
	DocumentIdentifier []byte `protobuf:"bytes,1,opt,name=document_identifier,json=documentIdentifier,proto3" json:"document_identifier,omitempty"`
}

func (m *GetInvoiceDocumentEnvelope) Reset()                    { *m = GetInvoiceDocumentEnvelope{} }
func (m *GetInvoiceDocumentEnvelope) String() string            { return proto.CompactTextString(m) }
func (*GetInvoiceDocumentEnvelope) ProtoMessage()               {}
func (*GetInvoiceDocumentEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetInvoiceDocumentEnvelope) GetDocumentIdentifier() []byte {
	if m != nil {
		return m.DocumentIdentifier
	}
	return nil
}

type ReceivedInvoices struct {
	Invoices []*invoice1.InvoiceDocument `protobuf:"bytes,1,rep,name=invoices" json:"invoices,omitempty"`
}

func (m *ReceivedInvoices) Reset()                    { *m = ReceivedInvoices{} }
func (m *ReceivedInvoices) String() string            { return proto.CompactTextString(m) }
func (*ReceivedInvoices) ProtoMessage()               {}
func (*ReceivedInvoices) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReceivedInvoices) GetInvoices() []*invoice1.InvoiceDocument {
	if m != nil {
		return m.Invoices
	}
	return nil
}

func init() {
	proto.RegisterType((*SendInvoiceEnvelope)(nil), "invoice.SendInvoiceEnvelope")
	proto.RegisterType((*GetInvoiceDocumentEnvelope)(nil), "invoice.GetInvoiceDocumentEnvelope")
	proto.RegisterType((*ReceivedInvoices)(nil), "invoice.ReceivedInvoices")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for InvoiceDocumentService service

type InvoiceDocumentServiceClient interface {
	SendInvoiceDocument(ctx context.Context, in *SendInvoiceEnvelope, opts ...grpc.CallOption) (*invoice1.InvoiceDocument, error)
	GetInvoiceDocument(ctx context.Context, in *GetInvoiceDocumentEnvelope, opts ...grpc.CallOption) (*invoice1.InvoiceDocument, error)
	GetReceivedInvoiceDocuments(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ReceivedInvoices, error)
}

type invoiceDocumentServiceClient struct {
	cc *grpc.ClientConn
}

func NewInvoiceDocumentServiceClient(cc *grpc.ClientConn) InvoiceDocumentServiceClient {
	return &invoiceDocumentServiceClient{cc}
}

func (c *invoiceDocumentServiceClient) SendInvoiceDocument(ctx context.Context, in *SendInvoiceEnvelope, opts ...grpc.CallOption) (*invoice1.InvoiceDocument, error) {
	out := new(invoice1.InvoiceDocument)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/SendInvoiceDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceDocumentServiceClient) GetInvoiceDocument(ctx context.Context, in *GetInvoiceDocumentEnvelope, opts ...grpc.CallOption) (*invoice1.InvoiceDocument, error) {
	out := new(invoice1.InvoiceDocument)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/GetInvoiceDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceDocumentServiceClient) GetReceivedInvoiceDocuments(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ReceivedInvoices, error) {
	out := new(ReceivedInvoices)
	err := grpc.Invoke(ctx, "/invoice.InvoiceDocumentService/GetReceivedInvoiceDocuments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InvoiceDocumentService service

type InvoiceDocumentServiceServer interface {
	SendInvoiceDocument(context.Context, *SendInvoiceEnvelope) (*invoice1.InvoiceDocument, error)
	GetInvoiceDocument(context.Context, *GetInvoiceDocumentEnvelope) (*invoice1.InvoiceDocument, error)
	GetReceivedInvoiceDocuments(context.Context, *google_protobuf1.Empty) (*ReceivedInvoices, error)
}

func RegisterInvoiceDocumentServiceServer(s *grpc.Server, srv InvoiceDocumentServiceServer) {
	s.RegisterService(&_InvoiceDocumentService_serviceDesc, srv)
}

func _InvoiceDocumentService_SendInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInvoiceEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).SendInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/SendInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).SendInvoiceDocument(ctx, req.(*SendInvoiceEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceDocumentService_GetInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceDocumentEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).GetInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/GetInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).GetInvoiceDocument(ctx, req.(*GetInvoiceDocumentEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceDocumentService_GetReceivedInvoiceDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceDocumentServiceServer).GetReceivedInvoiceDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceDocumentService/GetReceivedInvoiceDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceDocumentServiceServer).GetReceivedInvoiceDocuments(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _InvoiceDocumentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.InvoiceDocumentService",
	HandlerType: (*InvoiceDocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInvoiceDocument",
			Handler:    _InvoiceDocumentService_SendInvoiceDocument_Handler,
		},
		{
			MethodName: "GetInvoiceDocument",
			Handler:    _InvoiceDocumentService_GetInvoiceDocument_Handler,
		},
		{
			MethodName: "GetReceivedInvoiceDocuments",
			Handler:    _InvoiceDocumentService_GetReceivedInvoiceDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/invoice.proto",
}

func init() { proto.RegisterFile("invoice/invoice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x55, 0x8a, 0xf8, 0x91, 0x19, 0x68, 0xf2, 0x46, 0x15, 0xb2, 0x0a, 0x45, 0x81, 0x8b, 0xaa,
	0xa2, 0x76, 0x09, 0x5c, 0x8c, 0x5e, 0x31, 0xb6, 0x69, 0xf4, 0x02, 0x81, 0xda, 0x3b, 0x6e, 0x50,
	0xea, 0x7e, 0x75, 0x0d, 0xa9, 0x6d, 0xc5, 0x6e, 0x11, 0x42, 0x08, 0x89, 0x47, 0x80, 0x17, 0xe0,
	0x9d, 0x78, 0x00, 0x6e, 0x78, 0x02, 0x9e, 0x00, 0x2d, 0x8d, 0xdd, 0xae, 0x6b, 0x77, 0xe5, 0xd8,
	0xe7, 0xcb, 0x39, 0x27, 0xc7, 0x27, 0xe8, 0x9e, 0x90, 0x73, 0x25, 0x18, 0xd0, 0x6a, 0x25, 0xba,
	0x50, 0x56, 0xe1, 0x9b, 0xd5, 0x36, 0x6a, 0x70, 0xa5, 0x78, 0x0e, 0x34, 0xd3, 0x82, 0x66, 0x52,
	0x2a, 0x9b, 0x59, 0xa1, 0xa4, 0x59, 0x8c, 0x45, 0x07, 0x15, 0x5a, 0xee, 0x86, 0xb3, 0x31, 0x85,
	0xa9, 0xb6, 0x9f, 0x2b, 0xf0, 0x71, 0xb9, 0xb0, 0x36, 0x07, 0xd9, 0x36, 0x9f, 0x32, 0xce, 0xa1,
	0xa0, 0x4a, 0x97, 0xaf, 0x6f, 0xa0, 0x6a, 0x31, 0x90, 0xb6, 0x10, 0xe3, 0x19, 0x87, 0xb6, 0xa3,
	0x33, 0x74, 0xa3, 0xbb, 0xe4, 0x23, 0xda, 0x1b, 0x80, 0x1c, 0xf5, 0x16, 0x87, 0xa7, 0x72, 0x0e,
	0xb9, 0xd2, 0x80, 0x1f, 0x20, 0x54, 0x00, 0x13, 0x5a, 0x80, 0xb4, 0x26, 0x0c, 0xe2, 0x6b, 0xcd,
	0x9d, 0xfe, 0xca, 0x09, 0x7e, 0x86, 0x6e, 0x8d, 0x14, 0x9b, 0x4d, 0x41, 0xda, 0x10, 0xc5, 0x41,
	0xf3, 0x76, 0x1a, 0x12, 0x47, 0x5c, 0x71, 0x9d, 0x54, 0x78, 0xdf, 0x4f, 0x26, 0xaf, 0x51, 0x74,
	0x06, 0x76, 0x0d, 0xf7, 0x9a, 0x14, 0xed, 0xb9, 0xc9, 0xf7, 0x62, 0x04, 0xd2, 0x8a, 0xb1, 0x80,
	0x22, 0x0c, 0xe2, 0xa0, 0xb9, 0xd3, 0xc7, 0x0e, 0xea, 0x79, 0x24, 0x79, 0x85, 0x76, 0xfb, 0xc0,
	0x40, 0xcc, 0xc1, 0xf9, 0x2f, 0x8d, 0x55, 0x3e, 0x16, 0xb6, 0xaf, 0x34, 0xe6, 0x26, 0xd3, 0x7f,
	0x35, 0x54, 0x5f, 0x43, 0x07, 0x50, 0xcc, 0x05, 0x03, 0xcc, 0x2f, 0x04, 0xe4, 0x50, 0xdc, 0xf0,
	0xac, 0x1b, 0xe2, 0x8b, 0xb6, 0x6a, 0x26, 0xe1, 0xf7, 0xdf, 0x7f, 0x7f, 0xd6, 0x70, 0x72, 0xc7,
	0xdf, 0x87, 0x01, 0x39, 0xea, 0x06, 0x2d, 0xfc, 0x0d, 0xe1, 0xcb, 0xe1, 0xe0, 0x87, 0x9e, 0x69,
	0x7b, 0x72, 0x57, 0xc8, 0xb5, 0x4a, 0xb9, 0x47, 0x38, 0xf1, 0x72, 0x1c, 0x2c, 0xfd, 0xb2, 0x21,
	0xe7, 0xaf, 0x58, 0xa2, 0x83, 0x33, 0xb0, 0x6b, 0x89, 0x3a, 0x26, 0x83, 0xeb, 0x64, 0xd1, 0x50,
	0xe2, 0x2a, 0x45, 0x4e, 0xcf, 0x1b, 0x1a, 0xdd, 0xf7, 0xe2, 0xeb, 0x97, 0x91, 0x34, 0x4a, 0xf5,
	0x3a, 0xde, 0x5f, 0x55, 0x77, 0x53, 0x2f, 0xff, 0x04, 0x3f, 0x8e, 0x7e, 0x05, 0x98, 0xa3, 0xf0,
	0xd8, 0xf7, 0x35, 0x7e, 0x33, 0x88, 0x8f, 0xf3, 0xf3, 0x8e, 0xc5, 0x47, 0x6f, 0x7b, 0xc9, 0x09,
	0x42, 0x4b, 0x0c, 0xc7, 0x13, 0x6b, 0xb5, 0xe9, 0x52, 0xca, 0x85, 0x9d, 0xcc, 0x86, 0x84, 0xa9,
	0x29, 0x5d, 0xc2, 0x3d, 0xc9, 0xa2, 0xfd, 0x09, 0xe4, 0xb9, 0x7a, 0xb1, 0xec, 0x3f, 0x51, 0x12,
	0xd2, 0xeb, 0x1d, 0xd2, 0x21, 0x4f, 0xa2, 0xbb, 0xb9, 0x62, 0x59, 0x3e, 0x51, 0xc6, 0x76, 0x0f,
	0x3b, 0x87, 0x69, 0x2b, 0xa8, 0xa5, 0xbb, 0x99, 0xd6, 0xb9, 0x60, 0xe5, 0xdf, 0x43, 0x3f, 0x18,
	0x25, 0xbb, 0x97, 0x4e, 0xde, 0x3d, 0xdf, 0xa6, 0x46, 0xb9, 0x6a, 0x2f, 0x95, 0xe8, 0xca, 0x63,
	0xf5, 0xb5, 0xc3, 0x1b, 0x65, 0x54, 0x4f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x58, 0x51,
	0xa9, 0x1a, 0x04, 0x00, 0x00,
}
