// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package config

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"

	signature "github.com/centrifuge/go-substrate-rpc-client/v4/signature"

	types "github.com/centrifuge/go-substrate-rpc-client/v4/types"
)

// PodOperatorMock is an autogenerated mock type for the PodOperator type
type PodOperatorMock struct {
	mock.Mock
}

// FromJSON provides a mock function with given fields: json
func (_m *PodOperatorMock) FromJSON(json []byte) error {
	ret := _m.Called(json)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(json)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountID provides a mock function with given fields:
func (_m *PodOperatorMock) GetAccountID() *types.AccountID {
	ret := _m.Called()

	var r0 *types.AccountID
	if rf, ok := ret.Get(0).(func() *types.AccountID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AccountID)
		}
	}

	return r0
}

// GetURI provides a mock function with given fields:
func (_m *PodOperatorMock) GetURI() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// JSON provides a mock function with given fields:
func (_m *PodOperatorMock) JSON() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToKeyringPair provides a mock function with given fields:
func (_m *PodOperatorMock) ToKeyringPair() signature.KeyringPair {
	ret := _m.Called()

	var r0 signature.KeyringPair
	if rf, ok := ret.Get(0).(func() signature.KeyringPair); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(signature.KeyringPair)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *PodOperatorMock) Type() reflect.Type {
	ret := _m.Called()

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}

type NewPodOperatorMockT interface {
	mock.TestingT
	Cleanup(func())
}

// NewPodOperatorMock creates a new instance of PodOperatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPodOperatorMock(t NewPodOperatorMockT) *PodOperatorMock {
	mock := &PodOperatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
