// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package messenger

import mock "github.com/stretchr/testify/mock"

// MessageSenderFactoryMock is an autogenerated mock type for the MessageSenderFactory type
type MessageSenderFactoryMock struct {
	mock.Mock
}

// NewMessageSender provides a mock function with given fields: args
func (_m *MessageSenderFactoryMock) NewMessageSender(args *MessageSenderArgs) MessageSender {
	ret := _m.Called(args)

	var r0 MessageSender
	if rf, ok := ret.Get(0).(func(*MessageSenderArgs) MessageSender); ok {
		r0 = rf(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MessageSender)
		}
	}

	return r0
}

type NewMessageSenderFactoryMockT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMessageSenderFactoryMock creates a new instance of MessageSenderFactoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMessageSenderFactoryMock(t NewMessageSenderFactoryMockT) *MessageSenderFactoryMock {
	mock := &MessageSenderFactoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
