package userapi

CreateTransferDetailRequest
ToCreateTransferDetailPayload

UpdateTransferDetailRequest
ToUpdateTransferDetailPayload

GetRequest
GetVersionRequest

TransferDetailResponse
TransferDetailData

GetListRequest
TransferDetailListResponse